import "./globals.css";
import { Inter, Noto_Sans_Display } from "next/font/google";
import Navbar from "@/components/Navbar/Navbar";
import YouMayAlsoLike from "@/components/YouMayAlsoLike/YouMayAlsoLike";

const sans = Noto_Sans_Display({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={sans.className}>
        <Navbar />
        <div className="flex bg-[#EFF2F5] p-8">
          {children}
        </div>
        <YouMayAlsoLike/>
      </body>
    </html>
  );
}
