import "./globals.css";
import { Inter, Noto_Sans_Display } from "next/font/google";
import Navbar from "@/components/Navbar/Navbar";
import YouMayAlsoLike from "@/components/YouMayAlsoLike/YouMayAlsoLike";
import MobileNavbar from "@/components/Navbar/MobileNavbar";
import KoinXCard from "@/components/Cards/KoinXCard";
import TrendingCoinsCard from "@/components/Cards/TrendingCoins";

const sans = Noto_Sans_Display({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={sans.className}>

                <div className="hidden md:block text-black">
                    <Navbar />
                    <div className="bg-[#EFF2F5] p-8">
                        {children}
                        <YouMayAlsoLike />
                    </div>
                </div>

                <div className="block md:hidden text-black">
                    <MobileNavbar />
                    <div className=" bg-[#EFF2F5] px-4 pb-4 pt-10">
                        {children}
                        <YouMayAlsoLike />
                        <div className="flex flex-col space-y-5">
                            <KoinXCard />
                            <TrendingCoinsCard />
                        </div>
                    </div>
                </div>
                
            </body>
        </html>
    );
}
